import "bootstrap/dist/css/bootstrap.min.css";
import { fetchMovieByTitle, fetchMoviePlot } from "../movieData";
import { Navbar } from "../uiElements";
import React, { useEffect, useState } from "react";
import Link from "next/link";
import styles from "../../styles/movieDetails.module.css";
import Head from "next/head";

export async function getServerSideProps(context) {
  
  const { title } = context.params;
  const movie = await fetchMovieByTitle(title);
  const plotData = await fetchMoviePlot(movie.originalTitle, movie.releaseYear);

  console.log("plotData:", plotData);
  return {
    props: {
      movie: movie || null,
      plotData: plotData || null,
    },
  };
}


export default function MovieDetail({ movie, plotData }) {
  if (!movie) {
    return <div>Movie not found.</div>;
  }

  const [watchlist, setWatchlist] = useState([]);

useEffect(() => {
  const stored = localStorage.getItem("watchlist");
  if (stored) {
    setWatchlist(JSON.parse(stored));
  }
}, []);

  const addToWatchlist = () => {
  const exists = watchlist.some(item => item.id === movie.id);
  if (exists) {
    alert(`${movie.originalTitle} is already in your watchlist.`);
    return;
  }

  const updatedWatchlist = [...watchlist, movie];
  setWatchlist(updatedWatchlist);
  localStorage.setItem("watchlist", JSON.stringify(updatedWatchlist));
  alert(`${movie.originalTitle} has been added to your watchlist!`);
};

  return (
    <>
      <Head>
        <title>Movie-Finder | {movie.originalTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.png" />

      </Head>
    <Navbar />
    <div className={styles.detailsContainer}>
      <div className={styles.flexWrapper}>
        <img src={movie.bigPoster} alt={movie.originalTitle} className={styles.poster} />
        <div className={styles.infoWrapper}>
          <div className={styles.infoBlock}>
            <h1>{movie.originalTitle}</h1>
          </div>
          <div className={styles.infoBlock}>
            <p><strong>Released:</strong> {movie.releaseYear}</p>
            <p>{plotData?.plot ? plotData.plot : movie.overview}</p>
            <div className={styles.services}>
              {movie.streamingOptions?.map((option, index) => (
              <a
                key={index}
                href={option.link}
                target="_blank"
                rel="noopener noreferrer"
                className={styles.serviceLogo}
              >
                <img
                  src={option.service.imageSet.darkThemeImage}
                  alt={option.service.name}
                  title={option.service.name}
                />
              </a>
               ))}
              </div>

            
          </div>
          <div className={styles.buttonWrapper}>
          <Link className={styles.button} href="/">← Back to Movie List</Link>
          <button className={styles.button} onClick={addToWatchlist}>
                Add to Watchlist
              </button>
          </div>
        </div>
      </div>
    </div>
    </>
  );
  
}

