
import Head from "next/head";
import styles from "../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import {Navbar, DisplayMovies} from "../uiElements";
import React from "react";
import Link from "next/link";


export default function Home() {
  return (
    <>
      <Head>
        <title>Movie List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <Navbar />
      <main>
        <section>
        <h1>Movie Page</h1>
          <DisplayMovies />
        </section>
      </main>
      </div>
    </>
  );
}


