
import Head from "next/head";
import styles from "../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import {Navbar, DisplayMovies} from "./uiElements";
import React, { useEffect } from "react";
import { fetchMovieData } from "./movieData";

export default function Home({ topRatedMovies }) {
  useEffect(() => {
    const existing = localStorage.getItem("watchlist");
    if (!existing) {
      localStorage.setItem("watchlist", JSON.stringify([]));
    }
  }, []);

  
  return (
    <>
      <Head>
        <title>Movie-Finder | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <Navbar />
      <main>
        <section className={styles.movies}>
          <h1>Main Page</h1>
          <DisplayMovies topRatedMovies={topRatedMovies} />
        </section>
      </main>
      </div>
    </>
  );
}


export async function getServerSideProps() {
  const topRatedUrl = 'https://streaming-availability.p.rapidapi.com/shows/search/filters?country=ca&series_granularity=show&order_direction=desc&order_by=rating&year_min=2000&output_language=en&show_type=movie';

  const [topRated] = await Promise.all([
    fetchMovieData(topRatedUrl),
  ]);

  const randomizeAndLimit = (arr: any[], limit: number) =>
    arr.sort(() => 0.5 - Math.random()).slice(0, limit);

  return {
    props: {
      topRatedMovies: randomizeAndLimit(topRated, 10)
    },
  };
}